stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs: 
      - data/processed

  data_feature_scaling:
    cmd: python src/data_feature_scaling.py
    deps:
      - data/processed
      - src/data_feature_scaling.py
    outs:
      - data/scaled
  data_modeling:
    cmd: python src/data_modeling.py
    deps:
      - data/scaled
      - src/data_modeling.py
    outs:
      - models/best_model.pkl
  data_evaluation:
    cmd: python src/data_evaluation.py
    deps:
      - models/best_model.pkl
      - src/data_evaluation.py
    metrics:
      - metrics/metrics.json

